name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.15
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Test
      run: make test-with-coverage
    # - uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     files: coverage.out
